### ISSUE TITLE
Can't find installation

### ISSUE THREAD

**Issue by lukewis** [microsoft/azure-boards-vscode#79]
I'm searching for this extension in VSCode 1.36.1 on MacOS, but it's not showing up in the extensions list.  Has it been released?  Do I need to change any settings to be able to find this extension in the search?

**Comment by danhellem** [comment]
@lukewis no we have not released the extension yet to the marketplace. We are having some debate on how the long term funding will be met to support that extension. For now you can create a VSIX and install locally. We hope to have an update on the marketplace in a few weeks.

**Comment by yoyoys** [comment]
@danhellem is this project dead?

**Comment by alexcnichols** [comment]
Hi @yoyoys -- I've asked again internally about the prospect of picking this back up and bringing it across the starting line into the Marketplace with a proper maintainer behind it. For now, no change from what Dan mentioned above.
